local DribbleSpec = _G.DribbleSpec or Ext.Require("Shared/DribbleSpec/init.lua")
local Assertions = Ext.Require("Shared/DribbleSpec/Tests/Support/Assertions.lua")

DribbleSpec.describe("DribbleSpec Phase6 P6.1 fixture api", { tags = { "unit", "phase6", "fixture" } }, function()
    DribbleSpec.test("ctx exposes fixture surface", function(ctx)
        Assertions.Equals(type(ctx.fixture), "table", "fixture table")
        Assertions.Equals(type(ctx.fixture.character), "function", "fixture.character")
        Assertions.Equals(type(ctx.fixture.item), "function", "fixture.item")
        Assertions.Equals(type(ctx.fixture.entity), "function", "fixture.entity")
        Assertions.Equals(type(ctx.fixture.state), "table", "fixture.state table")
        Assertions.Equals(type(ctx.fixture.state.snapshot), "function", "fixture.state.snapshot")
        Assertions.Equals(type(ctx.fixture.state.restore), "function", "fixture.state.restore")
    end)
end)
