Ext.Require("Shared/DribbleSpec/Tests/Phase1/Smoke.test.lua")
Ext.Require("Shared/DribbleSpec/Tests/Phase1/P1_2_FailingReporting.test.lua")
Ext.Require("Shared/DribbleSpec/Tests/Phase1/P1_5_OnlyFocus.test.lua")
Ext.Require("Shared/DribbleSpec/Tests/Phase1/P1_8_BeforeAllFailureSkip.test.lua")
Ext.Require("Shared/DribbleSpec/Tests/Phase1/P1_9_AfterEachFailureCurrentOnly.test.lua")
Ext.Require("Shared/DribbleSpec/Tests/Phase1/P1_10_NestedDescribeOrder.test.lua")
Ext.Require("Shared/DribbleSpec/Tests/Phase1/ConsoleReporterFormatting.test.lua")
