local DribbleSpec = _G.DribbleSpec or Ext.Require("Shared/DribbleSpec/init.lua")
local Assertions = Ext.Require("Shared/DribbleSpec/Tests/Support/Assertions.lua")

DribbleSpec.describe("DribbleSpec Phase2 P2.5 help topic parsing", { tags = { "unit", "phase2", "cli" } }, function()
    DribbleSpec.test("parses explicit help topic token", function()
        local options = DribbleSpec._internal.parseOptions({ "dribbles", "--help", "tag" })
        Assertions.Equals(options.help, true, "help flag")
        Assertions.Equals(options.helpTopic, "tag", "help topic")
        Assertions.Equals(#options.unknownArgs, 0, "unknown args count")
    end)

    DribbleSpec.test("normalizes option-like help topic tokens", function()
        local contextOptions = DribbleSpec._internal.parseOptions({ "dribbles", "--help", "--context" })
        Assertions.Equals(contextOptions.helpTopic, "context", "context help topic")

        local tagOptions = DribbleSpec._internal.parseOptions({ "dribbles", "-h", "--tag" })
        Assertions.Equals(tagOptions.helpTopic, "tag", "tag help topic")

        local verboseOptions = DribbleSpec._internal.parseOptions({ "dribbles", "--help", "--verbose" })
        Assertions.Equals(verboseOptions.helpTopic, "verbose", "verbose help topic")
    end)

    DribbleSpec.test("keeps help topic unset when no topic is provided", function()
        local options = DribbleSpec._internal.parseOptions({ "dribbles", "--help" })
        Assertions.Equals(options.help, true, "help flag")
        Assertions.Equals(options.helpTopic, nil, "help topic nil")
    end)

    DribbleSpec.test("accepts shorthand command name token", function()
        local options = DribbleSpec._internal.parseOptions({ "d", "--help", "context" })
        Assertions.Equals(options.help, true, "help flag")
        Assertions.Equals(options.helpTopic, "context", "help topic")
        Assertions.Equals(#options.unknownArgs, 0, "unknown args count")
    end)

    DribbleSpec.test("treats removed manifest option as unknown args", function()
        local options = DribbleSpec._internal.parseOptions({ "dribbles", "--manifest", "MyTests.lua" })
        Assertions.Equals(#options.unknownArgs, 2, "unknown args count")
        Assertions.Equals(options.unknownArgs[1], "--manifest", "unknown option")
        Assertions.Equals(options.unknownArgs[2], "MyTests.lua", "unknown value")
    end)

    DribbleSpec.test("treats hidden json-out option as unknown args", function()
        local options = DribbleSpec._internal.parseOptions({ "dribbles", "--json-out", "results.json" })
        Assertions.Equals(#options.unknownArgs, 2, "unknown args count")
        Assertions.Equals(options.unknownArgs[1], "--json-out", "unknown option")
        Assertions.Equals(options.unknownArgs[2], "results.json", "unknown value")
    end)

    DribbleSpec.test("parses --verbose and -v flags", function()
        local longForm = DribbleSpec._internal.parseOptions({ "dribbles", "--verbose" })
        Assertions.Equals(longForm.verbose, true, "long flag")

        local shortForm = DribbleSpec._internal.parseOptions({ "dribbles", "-v" })
        Assertions.Equals(shortForm.verbose, true, "short flag")
    end)
end)
